### ISSUE TITLE
Deno 1.4 support

### ISSUE THREAD

**Issue by Danieliessen** [denodrivers/deno_mysql#72]
are you planning to add Deno 1.4 support anytime soon

**Comment by ccouzens** [comment]
Hey @Danieliessen , I've been using this with Deno 1.4 with no problems. Is there something that makes you think it's not supported on Deno 1.4?

**Comment by U-ways** [comment]
Hello @ccouzens,

For example, when you use [denodb](https://github.com/eveningkid/denodb/issues) with -`-unstable` flag, we get import type errors from `deno_mysql`:

![image](https://user-images.githubusercontent.com/17771168/94806410-cc01db80-03e5-11eb-9a2a-aadf81764715.png)

This due to the [TypeScript 3.8 import type changes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) 

I will submit a PR to fix this, feel free to edit if needed.
